# Sponsorship options for the project
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [arksong]
# patreon: ""
# ko_fi: ""
# tidelift: ""
# community_bridge: ""
# liberapay: ""
# issuehunt: ""
# otechie: ""
# lfx_crowdfunding: ""
# buy_me_a_coffee: ""
# thanks_dev: ""
# charityware: ""
# custom: ["https://example.com"]
