"""Type stubs for amos_link_py native module"""

from typing import Optional, Any, Dict

class NodeKind:
    """Node type classification for federation"""
    ROBOT: NodeKind
    SENSOR: NodeKind
    GATEWAY: NodeKind

class Reliability:
    """Message delivery reliability"""
    BEST_EFFORT: Reliability
    RELIABLE: Reliability

class History:
    """Message history policy"""
    @staticmethod
    def keep_last(depth: int) -> History: ...
    @staticmethod
    def keep_all(depth: int) -> History: ...

class QoS:
    """Quality of Service configuration"""
    def __init__(self, reliability: Reliability, history: History) -> None: ...
    @staticmethod
    def default() -> QoS: ...
    @staticmethod
    def sensor() -> QoS: ...
    @staticmethod
    def control() -> QoS: ...
    @staticmethod
    def state() -> QoS: ...

class Timestamp:
    """High-precision timestamp"""
    def __init__(self, secs: int, nanos: int) -> None: ...
    @staticmethod
    def now() -> Timestamp: ...
    @property
    def secs(self) -> int: ...
    @property
    def nanos(self) -> int: ...

class LinkMetrics:
    """Node performance metrics"""
    @property
    def published(self) -> int: ...
    @property
    def delivered(self) -> int: ...
    @property
    def dropped(self) -> int: ...
    @property
    def errors(self) -> int: ...
    def delivery_ratio(self) -> float: ...

class LinkNode:
    """Network node for pub/sub communication"""
    def __init__(self, peer_id: str, kind: NodeKind) -> None: ...
    @property
    def peer_id(self) -> str: ...
    @property
    def kind(self) -> NodeKind: ...
    def metrics(self) -> LinkMetrics: ...
    def publisher(self, topic: str) -> Publisher: ...
    def subscriber(self, pattern: str, qos: Optional[QoS] = None) -> Subscriber: ...
    def spawn_federation(self, period_ms: int) -> FederationTask: ...

class Publisher:
    """Message publisher"""
    @property
    def topic(self) -> str: ...
    def publish(self, data: bytes) -> None: ...
    def publish_json(self, obj: Any) -> None: ...

class ReceivedMessage:
    """Received message with metadata"""
    @property
    def topic(self) -> str: ...
    @property
    def peer_id(self) -> str: ...
    @property
    def seq(self) -> int: ...
    @property
    def timestamp(self) -> Timestamp: ...
    def payload(self) -> bytes: ...
    def payload_str(self) -> str: ...
    def payload_json(self) -> Any: ...

class Subscriber:
    """Message subscriber"""
    @property
    def pattern(self) -> str: ...
    def poll(self) -> Optional[ReceivedMessage]: ...
    def recv(self, timeout_secs: Optional[float] = None) -> Optional[ReceivedMessage]: ...
    def stats(self) -> Dict[str, int]: ...

class FederationTask:
    """Background peer discovery task"""
    def stop(self) -> None: ...

__version__: str
